/* Generated by Phoenix Tuner X */
package frc.robot.subsystems;

import static edu.wpi.first.units.Units.*;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.controls.ColorFlowAnimation;
import com.ctre.phoenix6.controls.LarsonAnimation;
import com.ctre.phoenix6.hardware.CANdle;
import com.ctre.phoenix6.signals.AnimationDirectionValue;
import com.ctre.phoenix6.signals.LarsonBounceValue;
import com.ctre.phoenix6.signals.RGBWColor;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

/** Subsystem that controls an addressable LED strip using a CANdle. */
public class LEDSubsystem extends SubsystemBase {
  private final CANBus kCANBus = new CANBus("driveTrainCANivore");
  private final CANdle m_candle = new CANdle(46, kCANBus);

  private final LarsonAnimation m_slot0Animation =
      new LarsonAnimation(8, 21)
          .withSlot(0)
          .withColor(new RGBWColor(32, 255, 245, 0))
          .withSize(3)
          .withBounceMode(LarsonBounceValue.Front)
          .withFrameRate(Hertz.of(25));

  private final ColorFlowAnimation m_slot1Animation =
      new ColorFlowAnimation(8, 21)
          .withSlot(0)
          .withColor(new RGBWColor(17, 255, 166, 0))
          .withDirection(AnimationDirectionValue.Forward)
          .withFrameRate(Hertz.of(25));

  public LEDSubsystem() {
    setDefaultCommand(updateLEDs());
  }

  /**
   * Updates the animations and LEDs of the CANdle.
   *
   * @return Command to run
   */
  public Command updateLEDs() {
    return run(
        () -> {
          m_candle.setControl(m_slot0Animation);
        });
  }
}
